/* Offscreen browser journeys for generation, portable saves and user-course records. */
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const { loadPlaywright, serve, installPilot, shot, noOverflow, ORIGIN } = require('./browser-smoke.cjs');
async function main() {
  const pw = loadPlaywright();
  if (!pw) throw new Error('Playwright is required for workshop validation');
  const browser = await pw.chromium.launch({ headless: true, channel: 'msedge' });
  const errors = [];
  try {
    for (const [label, width, height] of [['desktop', 1440, 900], ['phone', 390, 844], ['landscape', 844, 390]]) {
      const context = await browser.newContext({ viewport: { width, height }, locale: 'ko-KR', acceptDownloads: true });
      await serve(context);
      await context.addInitScript(() => {
        crypto.getRandomValues = array => { array.fill(41); return array; };
        if (!localStorage.getItem('chartflip.v1')) localStorage.setItem('chartflip.v1', JSON.stringify({ settings: { lang: 'ko', guide: false }, records: {} }));
      });
      const page = await context.newPage();
      page.on('pageerror', e => errors.push(label + ': ' + e.message));
      await page.goto(ORIGIN);
      await page.waitForFunction(() => window.Chartflip?.app);
      await page.click('#helpButton');
      await page.keyboard.press('Tab');
      assert.equal(await page.locator('#helpClose').evaluate(el => el === document.activeElement), true);
      await page.keyboard.press('Shift+Tab');
      assert.equal(await page.locator('#helpClose').evaluate(el => el === document.activeElement), true);
      await page.keyboard.press('Escape');
      await page.click('#langToggle');
      assert.equal(await page.locator('#langToggle').textContent(), 'KR');
      await page.click('#langToggle');
      await page.click('[data-tab="create"]');
      await page.waitForFunction(() => !document.getElementById('playMap').disabled, null, { timeout: 30000 });
      // Cancel at a known event-loop boundary, before a fast machine can finish all simulations.
      await page.evaluate(async () => {
        document.getElementById('generateMap').click();
        await new Promise(resolve => setTimeout(resolve, 0));
        const cancel = document.getElementById('cancelMap');
        if (cancel.hidden) throw new Error('Cancel control is not visible during generation');
        cancel.click();
      });
      await page.waitForFunction(() => !document.getElementById('generateMap').disabled);
      assert.match(await page.locator('#mapStatus').textContent(), /취소/);
      assert.equal(await page.locator('#playMap').isDisabled(), true);
      await page.click('#generateMap');
      await page.waitForFunction(() => !document.getElementById('playMap').disabled, null, { timeout: 30000 });
      await page.click('#mapSettings');
      assert.equal(await page.locator('#map-length').isVisible(), true);
      await page.locator('#map-coins').evaluate(input => {
        input.value = '90';
        input.dispatchEvent(new Event('input', { bubbles: true }));
        input.dispatchEvent(new Event('change', { bubbles: true }));
      });
      await page.waitForFunction(() => !document.getElementById('playMap').disabled, null, { timeout: 30000 });
      await page.click('#mapSettings');
      assert.equal(await page.locator('#map-length').isVisible(), false);
      await page.locator('#mapTitle').fill('R M P test map');
      const muted = await page.locator('#soundToggle').getAttribute('aria-pressed');
      await page.locator('#mapTitle').press('m');
      await page.locator('#mapTitle').press('p');
      await page.locator('#mapTitle').press('r');
      assert.equal(await page.locator('#soundToggle').getAttribute('aria-pressed'), muted);
      assert.equal(await page.evaluate(() => Chartflip.app.snapshot().screen), 'menu');
      await page.locator('#mapTitle').fill('Test map');
      const gold = await page.locator('#medal-gold').inputValue();
      const preview = await page.locator('#mapPreview').innerHTML();
      await page.click('#mapSettings');
      await page.reload();
      await page.waitForFunction(() => window.Chartflip?.app);
      assert.equal(await page.locator('#mapTitle').isVisible(), true, 'refresh restores the creation tab');
      assert.equal(await page.locator('#mapTitle').inputValue(), 'Test map', 'unsaved title survives');
      assert.equal(await page.locator('#medal-gold').inputValue(), gold);
      assert.equal(await page.locator('#mapPreview').innerHTML(), preview, 'refresh keeps the exact draft');
      assert.equal(await page.locator('#map-coins').inputValue(), '90');
      assert.equal(await page.locator('#map-coins').isVisible(), true, 'advanced panel remains open');
      assert.equal(await page.locator('#savedMaps .course').count(), 0, 'draft restoration does not save to the library');
      await page.click('#mapSettings');
      await page.locator('#medal-gold').fill('599');
      await page.click('#saveMap');
      assert.match(await page.locator('#mapStatus').textContent(), /금 < 은 < 동/);
      await page.locator('#medal-gold').fill(gold);
      await page.click('#saveMap');
      assert.match(await page.locator('#mapStatus').textContent(), /저장됨/);
      await noOverflow(page, label + ' editor');
      await shot(page, label + '-workshop');
      const downloadPromise = page.waitForEvent('download');
      await page.click('#exportMap');
      const download = await downloadPromise;
      const exported = await fs.readFile(await download.path(), 'utf8');
      const definition = await page.evaluate(text => Chartflip.maps.decode(text), exported);
      assert.equal(definition.coinLayout.length, 90);
      assert.equal(definition.parameters.coins, 90);
      await page.reload();
      await page.waitForFunction(() => window.Chartflip?.app);
      assert.equal(await page.locator('#courseList .course').count(), 15);
      await page.click('[data-tab="mine"]');
      await page.reload();
      await page.waitForFunction(() => window.Chartflip?.app);
      assert.equal(await page.locator('#savedMaps .course').isVisible(), true, 'refresh keeps the library tab');
      await page.click('#helpButton');
      await page.reload();
      await page.waitForFunction(() => window.Chartflip?.app);
      assert.equal(await page.locator('#helpScreen').isVisible(), true, 'help stays open across refresh');
      await page.click('#helpClose');
      assert.equal(await page.locator('#savedMaps .course').count(), 1);
      await noOverflow(page, label + ' library');
      await shot(page, label + '-maps');
      if (label === 'desktop') {
        await page.click('#savedMaps .course');
        await page.reload();
        await page.waitForFunction(() => window.Chartflip?.app);
        assert.equal(await page.evaluate(() => Chartflip.app.snapshot().screen), 'ready');
        assert.equal(await page.evaluate(() => Chartflip.app.snapshot().course), definition.id);
        await page.keyboard.press('Space');
        await page.waitForFunction(() => Chartflip.app.snapshot().tick > 200);
        await page.keyboard.press('Escape');
        const paused = await page.evaluate(() => Chartflip.app.snapshot());
        await page.reload();
        await page.waitForFunction(() => window.Chartflip?.app);
        assert.deepEqual(await page.evaluate(() => Chartflip.app.snapshot()), paused, 'refresh restores exact position, coins and run state paused');
        await page.click('#resumeButton');
        await page.waitForFunction(tick => Chartflip.app.snapshot().tick > tick + 30, paused.tick);
        await page.reload();
        await page.waitForFunction(() => window.Chartflip?.app);
        const refreshed = await page.evaluate(() => ({ current: Chartflip.app.snapshot(), saved: JSON.parse(sessionStorage.getItem('chartflip.session.v1')).race }));
        assert.equal(refreshed.current.screen, 'paused', 'refresh during a live race pauses it');
        assert.equal(refreshed.current.tick, refreshed.saved.tick, 'refresh restores the last simulated tick');
        await page.evaluate(installPilot);
        await page.click('#resumeButton');
        await page.locator('#resultScreen:not([hidden])').waitFor({ timeout: 60000 });
        assert.equal(await page.locator('#nextButton').isVisible(), false);
        const record = await page.evaluate(id => JSON.parse(localStorage.getItem('chartflip.v1')).records[id], definition.id);
        assert.ok(record.time > 0 && record.flips.length > 0 && record.boosts.length > 0);
        const resultTime = await page.locator('#resultTime').textContent();
        await page.reload();
        await page.waitForFunction(() => window.Chartflip?.app);
        assert.equal(await page.locator('#resultScreen').isVisible(), true);
        assert.equal(await page.locator('#resultTime').textContent(), resultTime);
        await page.evaluate(installPilot);
        await page.click('#retryButton');
        await page.waitForFunction(() => document.getElementById('delta').textContent.length > 0, null, { timeout: 10000 });
        await page.keyboard.press('Escape');
        await page.click('#menuButton');
        await page.click('#savedMaps .saved-actions button:first-child');
        await page.click('#mapSettings');
        assert.equal(await page.locator('#map-coins').inputValue(), '90');
        await page.click('#mapSettings');
        await page.locator('#mapTitle').fill('Renamed map');
        await page.click('#saveMap');
        const same = await page.evaluate(id => JSON.parse(localStorage.getItem('chartflip.v1')).records[id], definition.id);
        assert.deepEqual(same, record);
        await page.click('[data-tab="mine"]');
        await page.click('#savedMaps .saved-actions button:last-child');
        assert.equal(await page.locator('#savedMaps .course').count(), 0);
        await page.click('#undoMap');
        assert.equal(await page.locator('#savedMaps .course').count(), 1);
        await page.locator('#importMap').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":900}') });
        await page.waitForFunction(() => document.getElementById('libraryStatus').textContent.includes('맵 파일을 확인'));
        await page.click('#savedMaps .saved-actions button:last-child');
        await page.evaluate(async text => {
          const input = document.getElementById('importMap');
          const transfer = new DataTransfer();
          transfer.items.add(new File([text], 'map.json', { type: 'application/json' }));
          input.files = transfer.files;
          input.dispatchEvent(new Event('change', { bubbles: true }));
          await new Promise(resolve => setTimeout(resolve, 0));
          const cancel = document.getElementById('cancelImport');
          if (cancel.hidden) throw new Error('Cancel control is not visible during import');
          cancel.click();
        }, exported);
        await page.waitForFunction(() => !document.getElementById('importMap').disabled);
        assert.equal(await page.locator('#savedMaps .course').count(), 0);
        await page.locator('#importMap').setInputFiles({ name: 'map.json', mimeType: 'application/json', buffer: Buffer.from(exported) });
        await page.waitForFunction(() => document.getElementById('libraryStatus').textContent.includes('저장됨'));
        assert.equal(await page.locator('#savedMaps .course').count(), 1);
        const imported = await page.evaluate(() => Chartflip.maps.library(localStorage).maps[0]);
        assert.deepEqual(imported, definition);
        await page.click('#savedMaps .saved-actions button:first-child');
        await page.evaluate(() => {
          const original = Storage.prototype.setItem;
          Storage.prototype.setItem = function (key, value) { if (key === 'chartflip.maps.v1') throw new DOMException('Quota', 'QuotaExceededError'); return original.call(this, key, value); };
        });
        await page.click('#saveMap');
        assert.match(await page.locator('#mapStatus').textContent(), /파일로 저장/);
        const backup = page.waitForEvent('download'); await page.click('#exportMap'); await backup;
      }
      await context.close();
    }
  } finally { await browser.close(); }
  assert.deepEqual(errors, []);
  console.log('workshop smoke: ok (three layouts, generation/cancel, save/export/import, records/ghost, storage failure)');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
